# Generated by Django 6.0.7 on 2026-07-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(default="MyInvento IMS", max_length=200),
                ),
                (
                    "company_email",
                    models.EmailField(default="admin@myinvento.com", max_length=254),
                ),
                (
                    "company_phone",
                    models.CharField(default="+977-1-4200000", max_length=20),
                ),
                ("company_address", models.TextField(default="Kathmandu, Nepal")),
                ("currency_code", models.CharField(default="NPR", max_length=10)),
                ("currency_symbol", models.CharField(default="रू", max_length=5)),
                (
                    "default_valuation_method",
                    models.CharField(
                        choices=[
                            ("FIFO", "FIFO (First In, First Out)"),
                            ("LIFO", "LIFO (Last In, First Out)"),
                        ],
                        default="FIFO",
                        max_length=10,
                    ),
                ),
                ("low_stock_threshold", models.IntegerField(default=10)),
                ("overstock_threshold", models.IntegerField(default=500)),
                ("auto_reorder_enabled", models.BooleanField(default=False)),
                ("require_purchase_order_approval", models.BooleanField(default=True)),
                ("enable_batch_tracking", models.BooleanField(default=True)),
                ("enable_serial_tracking", models.BooleanField(default=False)),
                ("session_timeout_minutes", models.IntegerField(default=60)),
                ("max_login_attempts", models.IntegerField(default=5)),
                ("lockout_duration_minutes", models.IntegerField(default=15)),
                ("enable_email_notifications", models.BooleanField(default=False)),
                ("enable_low_stock_alerts", models.BooleanField(default=True)),
                ("enable_expiry_alerts", models.BooleanField(default=True)),
                ("expiry_alert_days", models.IntegerField(default=30)),
                (
                    "default_tax_rate",
                    models.DecimalField(decimal_places=2, default=13.0, max_digits=5),
                ),
                (
                    "receipt_footer_text",
                    models.CharField(
                        default="Thank you for shopping with us!", max_length=300
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={},
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("warehouse", "Warehouse"),
                    ("sales", "Sales"),
                    ("purchasing", "Purchasing"),
                    ("auditor", "Auditor"),
                ],
                default="sales",
                max_length=20,
            ),
        ),
    ]
