# Generated by Django 6.0.7 on 2026-07-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_systemsettings_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('warehouse', 'Warehouse'), ('sales', 'Sales'), ('purchasing', 'Purchasing'), ('auditor', 'Auditor'), ('customer', 'Customer')], default='sales', max_length=20),
        ),
    ]
