# Generated by Django 6.0.7 on 2026-07-30 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_category_name'),
        ('inventory', '0003_alter_warehouse_name'),
        ('purchasing', '0003_reorderrule_uuid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reorderrule',
            unique_together={('product', 'variant', 'warehouse')},
        ),
    ]
