# Generated by Django 6.0.7 on 2026-07-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Online image URL (e.g. from Google Images, Amazon, etc.)', max_length=500),
        ),
    ]
