# Generated by Django 6.0.7 on 2026-07-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_saleschannel_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True),
        ),
    ]
